export const COMPANY_PROFILES = {
  '2288105280': {
    cmpNm: '유큐브',
    region: '서울',
    companySize: '중소기업',
    industry: '정보통신업',
    employeeCount: 177,
    sales: 450,
    yearsInBusiness: 6,
    isSme: true,
    isSmallBusiness: false,
    isVenture: true,
    hasInnobiz: true,
    hasMainbiz: false,
    hasClosedStatus: false,
    isNonprofit: false,
    isFinanceIndustry: false,
  },
  '6058189115': {
    cmpNm: '유림이엔씨',
    region: '부산',
    companySize: '중견기업',
    industry: '건설업',
    employeeCount: 106,
    sales: 662,
    yearsInBusiness: 18,
    isSme: false,
    isSmallBusiness: false,
    isVenture: false,
    hasInnobiz: false,
    hasMainbiz: false,
    hasClosedStatus: false,
    isNonprofit: false,
    isFinanceIndustry: false,
  },
  '3078130710': {
    cmpNm: '한국바이오켐제약',
    region: '세종',
    companySize: '중소기업',
    industry: '제조업',
    employeeCount: 134,
    sales: 1339,
    yearsInBusiness: 17,
    isSme: true,
    isSmallBusiness: false,
    isVenture: false,
    hasInnobiz: true,
    hasMainbiz: true,
    hasClosedStatus: false,
    isNonprofit: false,
    isFinanceIndustry: false,
  },
  '0000000001': {
    cmpNm: '그린푸드 영농조합법인',
    region: '전북',
    companySize: '중소기업',
    industry: '농업',
    employeeCount: 25,
    sales: 4000000000,
    yearsInBusiness: 10,
    isSme: true,
    isExporter: true,
    hasMainbiz: true,
  },
  '0000000002': {
    cmpNm: '테크스타트 주식회사',
    region: '서울',
    companySize: '중소기업',
    industry: 'IT',
    employeeCount: 12,
    sales: 1100000000,
    yearsInBusiness: 4,
    isSme: true,
    isVenture: true,
    isYouth: true,
    hasInnobiz: true,
    hasResearchDept: true,
    registeredPatents: 2,
  },
  '0000000003': {
    cmpNm: '스마트팩토리 주식회사',
    region: '부산',
    companySize: '중소기업',
    industry: '제조업',
    employeeCount: 33,
    sales: 12000000000,
    yearsInBusiness: 20,
    isSme: true,
    isVenture: true,
    isExporter: true,
    hasInnobiz: true,
    hasMainbiz: true,
  },
  '0000000004': {
    cmpNm: '실버케어 협동조합',
    region: '인천',
    companySize: '소상공인',
    employeeCount: 4,
    sales: 200000000,
    yearsInBusiness: 8,
    isSmallBusiness: true,
    isDisabledOwned: true,
  },
  '0000000005': {
    cmpNm: '기쁨푸드',
    region: '서울',
    companySize: '소상공인',
    employeeCount: 4,
    sales: 100000000,
    yearsInBusiness: 2,
    isSmallBusiness: true,
    isStartup: true,
    isYouth: true,
  },
};

export const getCompanyProfileByBizNo = (bizno) => {
  if (!bizno) return null;
  const profile = COMPANY_PROFILES[String(bizno)];
  return profile ? { ...profile } : null;
};