// 모의 메뉴 데이터 (테스트용) TODO : 삭제예정
export const mockMenuData = {
  'menuId': 'M_PIIO_00063',
  'menuNm': '사용자 최상위메뉴',
  'intgSysSeCd': 'PIIO',
  'menuUseTrgtSeCd': 'USR',
  'upMenuId': null,
  'iconClssNm': null,
  'sortSeq': 0,
  'upendMenuExpsrYn': 'N',
  'lfsdMenuExpsrYn': 'N',
  'scrnUseYn': 'Y',
  'scrnId': 'S_PIIO_00063',
  'bbsNo': null,
  'scrnUrlAddr': '/',
  'scrnTypeCd': 'M',
  'upScrnId': null,
  'useYn': 'Y',
  'depth': 0,
  'children': [
    {
      'menuId': 'M_PIIO_00064',
      'menuNm': '지원사업',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 1,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00064',
      'bbsNo': null,
      'scrnUrlAddr': 'req',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00069',
          'menuNm': 'AI 스마트 검색',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'N',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00069',
          'bbsNo': null,
          'scrnUrlAddr': 'ai',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00064',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00074',
              'menuNm': 'AI 스마트 검색',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00069',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'N',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00074',
              'bbsNo': null,
              'scrnUrlAddr': 'ai-smart-search',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00069',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00076',
          'menuNm': '사업공고',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00076',
          'bbsNo': null,
          'scrnUrlAddr': 'pbanc',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00071',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00077',
          'menuNm': '정책금융',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00077',
          'bbsNo': null,
          'scrnUrlAddr': 'UI_USR_L_030',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00072',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00094',
          'menuNm': '입주기업 모집공고',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 5,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00026',
          'bbsNo': 57,
          'scrnUrlAddr': 'UI_USR_L_180',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00020',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00091',
          'menuNm': '주택특별공급 사업공고',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 6,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00091',
          'bbsNo': null,
          'scrnUrlAddr': 'UI_USR_L_150',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00083',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00075',
          'menuNm': '지원사업 소개',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 7,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00075',
          'bbsNo': null,
          'scrnUrlAddr': 'sprt',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00064',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00073',
      'menuNm': '증명서 발급',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 2,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00073',
      'bbsNo': null,
      'scrnUrlAddr': 'crtf',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00078',
          'menuNm': '발급',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00073',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00078',
          'bbsNo': null,
          'scrnUrlAddr': 'UI_USR_L_040',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00073',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00079',
          'menuNm': '발급 진위 확인',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00073',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00079',
          'bbsNo': null,
          'scrnUrlAddr': 'UI_USR_L_050',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00073',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00080',
          'menuNm': '기타증명서',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00073',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00080',
          'bbsNo': null,
          'scrnUrlAddr': 'UI_USR_L_060',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00073',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00090',
          'menuNm': '소재부품장비·뿌리기술·전문연구사업자 조회',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00073',
          'iconClssNm': null,
          'sortSeq': 4,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00090',
          'bbsNo': null,
          'scrnUrlAddr': 'UI_USR_L_140',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00083',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00065',
      'menuNm': '정책·법령 정보',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 3,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00065',
      'bbsNo': null,
      'scrnUrlAddr': 'plcy',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00081',
          'menuNm': '정책정보',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00065',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00081',
          'bbsNo': null,
          'scrnUrlAddr': 'reprt',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00065',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00084',
              'menuNm': '정책뉴스',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00081',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00144',
              'bbsNo': 64,
              'scrnUrlAddr': 'plcyNews',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00020',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00085',
              'menuNm': '행사정보',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00081',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00023',
              'bbsNo': 51,
              'scrnUrlAddr': 'UI_USR_L_190',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00020',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00086',
              'menuNm': '월간 중기누리',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00081',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00027',
              'bbsNo': 56,
              'scrnUrlAddr': 'UI_USR_L_100',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00020',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00082',
          'menuNm': '법령정보',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00065',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00082',
          'bbsNo': null,
          'scrnUrlAddr': 'icr',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00065',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00168',
              'menuNm': '중기부 소관 법령',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00168',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_130',
              //'scrnUrlAddr': 'https://www.mss.go.kr/site/smba/contents/view.do?menuCd=20103010000002024122811&siteCd=smba',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00082',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00166',
              'menuNm': '중소기업 주요제도',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00166',
              'bbsNo': null,
              'scrnUrlAddr': 'https://www.mss.go.kr/site/smba/contents/view.do?menuCd=20103040000002024122824&siteCd=smba',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00082',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            
            {
              'menuId': 'M_PIIO_00087',
              'menuNm': '입법·행정예고/고시',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00025',
              'bbsNo': 55,
              'scrnUrlAddr': 'UI_USR_L_110',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00020',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00088',
              'menuNm': '품목별 법정의무 인증제도',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00088',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_120',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00083',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00164',
          'menuNm': '기타 활용 서식',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00065',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'N',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00164',
          'bbsNo': null,
          'scrnUrlAddr': 'etcForm',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00065',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00066',
      'menuNm': '데이터 개방',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 4,
      'upendMenuExpsrYn': 'N',
      'lfsdMenuExpsrYn': 'N',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00066',
      'bbsNo': null,
      'scrnUrlAddr': 'do',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00095',
          'menuNm': '정책정보 개방',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00066',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00095',
          'bbsNo': null,
          'scrnUrlAddr': 'opn',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00066',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00067',
      'menuNm': '고객지원',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 5,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00067',
      'bbsNo': null,
      'scrnUrlAddr': 'cs',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00099',
          'menuNm': '고객센터',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00067',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00099',
          'bbsNo': null,
          'scrnUrlAddr': 'csc',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00067',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00101',
              'menuNm': '공지사항',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00101',
              'bbsNo': 1,
              'scrnUrlAddr': 'notice',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00102',
              'menuNm': '자주 묻는 질문',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00031',
              'bbsNo': 5,
              'scrnUrlAddr': 'faq',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00021',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00103',
              'menuNm': '문의하기',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00103',
              'bbsNo': 4,
              'scrnUrlAddr': 'qna',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00104',
              'menuNm': '콜센터안내',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00104',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_340',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00105',
              'menuNm': '고객 만족도 조사',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 5,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00105',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_R_341',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00100',
          'menuNm': '이용안내',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00067',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00100',
          'bbsNo': null,
          'scrnUrlAddr': 'info',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00067',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00106',
              'menuNm': '플랫폼 소개',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00100',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00106',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_R_350',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00100',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00107',
              'menuNm': '이용가이드',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00100',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00107',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_R_360',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00100',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00083',
          'menuNm': '더 많은 서비스',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00067',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'N',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00083',
          'bbsNo': null,
          'scrnUrlAddr': 'mor',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00126',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00149',
              'menuNm': '기업가정신',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00083',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00149',
              'bbsNo': null,
              'scrnUrlAddr': 'entrSpt',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00083',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00092',
          'menuNm': '유관시스템 둘러보기',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00067',
          'iconClssNm': null,
          'sortSeq': 6,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00092',
          'bbsNo': null,
          'scrnUrlAddr': 'UI_USR_L_160',
          'scrnTypeCd': 'T',
          'upScrnId': 'S_PIIO_00083',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00167',
          'menuNm': '데이터 개방',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00067',
          'iconClssNm': null,
          'sortSeq': 8,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00167',
          'bbsNo': null,
          'scrnUrlAddr': 'opndata',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00067',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00096',
              'menuNm': 'API 안내',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00167',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00096',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_210',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00095',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00097',
              'menuNm': '인증키 신청',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00167',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00097',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_220',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00095',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00098',
              'menuNm': 'API Q&A',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00167',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00098',
              'bbsNo': 67,
              'scrnUrlAddr': 'UI_USR_L_230',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00095',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00127',
              'menuNm': '속보성 대시보드',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00167',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00127',
              'bbsNo': null,
              'scrnUrlAddr': 'https://www.bizinfo.go.kr/dashboard.do',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00066',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00068',
      'menuNm': '마이 비즈니스',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 5,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00068',
      'bbsNo': null,
      'scrnUrlAddr': 'mb',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00108',
          'menuNm': '서비스 이용이력',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00108',
          'bbsNo': null,
          'scrnUrlAddr': 'dash',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00112',
              'menuNm': '나의 대시보드',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00112',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_480',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00108',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00114',
              'menuNm': '지원사업 신청 현황',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'N',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00114',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_520',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00108',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00113',
              'menuNm': '증명서 발급 조회',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00113',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_510',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00108',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00123',
              'menuNm': '관심 공고 등록',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00123',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_530',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00111',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00122',
              'menuNm': '문의 관리',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'N',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00122',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_470',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00110',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00124',
              'menuNm': '나의 알림',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00124',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_540',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00111',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00125',
              'menuNm': 'Open API 신청내역',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 5,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00125',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_L_550',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00111',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00119',
              'menuNm': '기업정보 관리',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 7,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00119',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_R_450',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00110',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00109',
          'menuNm': '회원정보관리',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00109',
          'bbsNo': null,
          'scrnUrlAddr': 'mbr',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00115',
              'menuNm': '회원정보변경',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00115',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_R_410',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00116',
              'menuNm': '비밀번호 수정',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00116',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_R_420',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00117',
              'menuNm': '인증수단 재설정',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'N',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00117',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_W_430',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00118',
              'menuNm': '회원탈퇴',
              'intgSysSeCd': 'PIIO',
              'menuUseTrgtSeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00118',
              'bbsNo': null,
              'scrnUrlAddr': 'UI_USR_R_440',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00110',
          'menuNm': '기업정보관리',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'N',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00110',
          'bbsNo': null,
          'scrnUrlAddr': 'cmp',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
        {
          'menuId': 'M_PIIO_00111',
          'menuNm': '서비스 이용이력',
          'intgSysSeCd': 'PIIO',
          'menuUseTrgtSeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 4,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'N',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00111',
          'bbsNo': null,
          'scrnUrlAddr': 'hsty',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00152',
      'menuNm': '통합검색',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 10,
      'upendMenuExpsrYn': 'N',
      'lfsdMenuExpsrYn': 'N',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00152',
      'bbsNo': null,
      'scrnUrlAddr': 'totalSearch',
      'scrnTypeCd': 'T',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [],
    },
    {
      'menuId': 'M_PIIO_00153',
      'menuNm': '이메일주소 무단수집거부 안내',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 50,
      'upendMenuExpsrYn': 'N',
      'lfsdMenuExpsrYn': 'N',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00153',
      'bbsNo': null,
      'scrnUrlAddr': 'emailRejection',
      'scrnTypeCd': 'T',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [],
    },
    {
      'menuId': 'M_PIIO_00154',
      'menuNm': '저작권 정책',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 51,
      'upendMenuExpsrYn': 'N',
      'lfsdMenuExpsrYn': 'N',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00154',
      'bbsNo': null,
      'scrnUrlAddr': 'copyrightPolicy',
      'scrnTypeCd': 'T',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [],
    },
    {
      'menuId': 'M_PIIO_00155',
      'menuNm': '웹접근성 정책',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 52,
      'upendMenuExpsrYn': 'N',
      'lfsdMenuExpsrYn': 'N',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00155',
      'bbsNo': null,
      'scrnUrlAddr': 'webAccessibilityPolicy',
      'scrnTypeCd': 'T',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [],
    },
    {
      'menuId': 'M_PIIO_00156',
      'menuNm': '이용약관',
      'intgSysSeCd': 'PIIO',
      'menuUseTrgtSeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 53,
      'upendMenuExpsrYn': 'N',
      'lfsdMenuExpsrYn': 'N',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00156',
      'bbsNo': null,
      'scrnUrlAddr': 'termsOfUse',
      'scrnTypeCd': 'T',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [],
    },
  ],
};