export const ENTREPRENEURSHIP_AWARD_DATA = [
  { year: 2017, honor: '중소벤처기업부 장관 표창', affiliation: '덕성여대 산학협력단/교수', name: '주재만' },
  { year: 2017, honor: '중소벤처기업부 장관 표창', affiliation: '국민대학교/교수', name: '김도현' },
  { year: 2017, honor: '중소벤처기업부 장관 표창', affiliation: '㈜르호봇비즈니스인큐베이터/기업가센터장', name: '김영록' },
  { year: 2017, honor: '중소벤처기업부 장관 표창', affiliation: '건양대학교/교수', name: '김경한' },
  { year: 2017, honor: '중소벤처기업부 장관 표창', affiliation: '대전창조경제혁신센터/주임', name: '김군태' },
  { year: 2017, honor: '중소벤처기업부 장관 표창', affiliation: '인하대학교 기업가센터(단체)', name: '' },
  { year: 2017, honor: '중소벤처기업부 장관 표창', affiliation: '어썸스쿨(단체)', name: '' },

  { year: 2018, honor: '중소벤처기업부 장관 표창', affiliation: '대구가톨릭대학교/교수', name: '금용필' },
  { year: 2018, honor: '중소벤처기업부 장관 표창', affiliation: '(주)시누스/대표', name: '김도영' },
  { year: 2018, honor: '중소벤처기업부 장관 표창', affiliation: '한국디지털미디어고등학교/교사', name: '남승완' },
  { year: 2018, honor: '중소벤처기업부 장관 표창', affiliation: '대구경북과학기술원/교수', name: '이공래' },
  { year: 2018, honor: '중소벤처기업부 장관 표창', affiliation: '화천정보산업고등학교/교사', name: '이인주' },
  { year: 2018, honor: '중소벤처기업부 장관 표창', affiliation: '동서울대학교/교수', name: '장규순' },
  { year: 2018, honor: '중소벤처기업부 장관 표창', affiliation: '[단체]한국교통대학교/총장', name: '박준훈' },
  { year: 2018, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '소상공인시장진흥공단/과장', name: '강영욱' },
  { year: 2018, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '인하대학교/교수', name: '유홍성' },
  { year: 2018, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '경주여자정보고등학교/교사', name: '이정아' },
  { year: 2018, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '충주상업고등학교/교사', name: '정규한' },
  { year: 2018, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '[단체]경민대학교산학협력단/산학협력단장', name: '김환철' },

  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '유성고등학교(現 교육부)/교사', name: '박상준' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '한밭대학교/교수', name: '송우용' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '동국대학교/교수', name: '전병훈' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '충북대학교/산학협력중점교수', name: '최유길' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '(사)창업지원네트워크/이사장', name: '하상용' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '㈜워크숍/대표이사', name: '홍성재' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '연세대학교', name: '김용학' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '경민대학교 산학협력단', name: '김환철' },
  { year: 2019, honor: '중소벤처기업부 장관 표창', affiliation: '㈜엔피프틴', name: '허제\n류선종' },
  { year: 2019, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '서울산업진흥원/책임', name: '장성훈' },
  { year: 2019, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '춘천사회혁신센터/매니저', name: '채희제' },
  { year: 2019, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '해동엔지니어링/대표이사', name: '최준호' },
  { year: 2019, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '대진대학교 산학협력단', name: '김성수' },
  { year: 2019, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '캠퍼스멘토', name: '안광배' },

  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '건국대학교/교수', name: '권혁' },
  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '과학기술연합대학원대학교/교수', name: '박정민' },
  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '소셜혁신연구소 사회적협동조합/이사장', name: '안지훈' },
  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '안산공업고등학교/교사', name: '조대범' },
  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '㈜비씨에이컴퍼니/공동대표', name: '주창림' },
  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '(재)서울산업진흥원', name: '장영승' },
  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '광운대학교 산학협력단', name: '유정호' },
  { year: 2020, honor: '중소벤처기업부 장관 표창', affiliation: '사단법인 제이에이코리아', name: '오종남' },
  { year: 2020, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '대구보건고등학교/교사', name: '곽우은' },
  { year: 2020, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '국민대학교/교수', name: '김종성' },
  { year: 2020, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '(재)서울산업진흥원/선임', name: '박유선' },
  { year: 2020, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '㈜이엔아이그룹', name: '김남균' },
  { year: 2020, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '영산대학교 스타트업센터', name: '김찬길' },

  { year: 2021, honor: '장관표창', affiliation: '강원대학교/연구교수', name: '김영지' },
  { year: 2021, honor: '장관표창', affiliation: '한국과학기술원(KAIST)/교수', name: '노수홍' },
  { year: 2021, honor: '장관표창', affiliation: '경상국립대학교/교수', name: '성상현' },
  { year: 2021, honor: '장관표창', affiliation: '기업가정신 문화센터/대표', name: '송정현' },
  { year: 2021, honor: '장관표창', affiliation: '서울과학기술대학교 산학협력단/교수', name: '심경수' },
  { year: 2021, honor: '장관표창', affiliation: '인천세무고등학교/교사', name: '이영순' },
  { year: 2021, honor: '장관표창', affiliation: '순천대학교/교수', name: '이재은' },
  { year: 2021, honor: '장관표창', affiliation: '건국대학교/교수', name: '이진홍' },
  { year: 2021, honor: '장관표창', affiliation: '경인여자대학교/교수', name: '허제강' },
  { year: 2021, honor: '이사장표창', affiliation: '경동대학교/교수', name: '노기엽' },
  { year: 2021, honor: '이사장표창', affiliation: '루트임팩트/팀장', name: '박연경' },
  { year: 2021, honor: '이사장표창', affiliation: '(사)청년창업가협회(단체)', name: '' },
  { year: 2021, honor: '이사장표창', affiliation: '탱커 주식회사/대표', name: '임현서' },
  { year: 2021, honor: '이사장표창', affiliation: '주식회사 울타리스쿨(단체)', name: '' },

  { year: 2022, honor: '장관 표창', affiliation: '한밭대학교/선임매니저', name: '곽연' },
  { year: 2022, honor: '장관 표창', affiliation: '계명대학교/교수', name: '김창완' },
  { year: 2022, honor: '장관 표창', affiliation: '고려대학교/교수', name: '신호정' },
  { year: 2022, honor: '장관 표창', affiliation: '(재)경기도경제과학진흥원/팀장', name: '안경우' },
  { year: 2022, honor: '장관 표창', affiliation: '한국관광고등학교/교사', name: '이창수' },
  { year: 2022, honor: '장관 표창', affiliation: '동국대학교/교수', name: '이창영' },
  { year: 2022, honor: '장관 표창', affiliation: '경희대학교/교수', name: '정치화' },
  { year: 2022, honor: '장관 표창', affiliation: '한양대학교기술지주회사/본부장', name: '최경철' },
  { year: 2022, honor: '장관 표창', affiliation: '중소벤처기업진흥공단/팀장', name: '한동국' },
  { year: 2022, honor: '이사장표창', affiliation: '서울소셜벤처허브/매니저', name: '구선미' },
  { year: 2022, honor: '이사장표창', affiliation: '한국여성리더십센터/대표', name: '김경희' },
  { year: 2022, honor: '이사장표창', affiliation: '강서대학교/교수', name: '이득규' },
  { year: 2022, honor: '이사장표창', affiliation: '경희대학교/교수', name: '이상규' },
  { year: 2022, honor: '이사장표창', affiliation: '한국자산관리공사(단체)', name: '' },

  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '우송대학교/교수', name: '구인혁' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '영산대학교/교수', name: '김정래' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '㈜서정코리아/대표', name: '서정철' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '고양송산중학교/교사', name: '유승목' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '㈜미텔슈탄트/대표', name: '조동인' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '(재)충남창조경제혁신센터(단체)', name: '' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '(재)한국연구재단(단체)', name: '' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '대진분체산업(단체)', name: '' },
  { year: 2023, honor: '중소벤처기업부 장관 표창', affiliation: '㈜에스티엔(단체)', name: '' },
  { year: 2023, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '㈜코코넛사일로/대표', name: '김승용' },
  { year: 2023, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '㈜마롱컴퍼니/대표', name: '이어진' },
  { year: 2023, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '㈜오픈놀(단체)', name: '' },
  { year: 2023, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '㈜힐링사운드(단체)', name: '' },

  { year: 2024, honor: '중소벤처기업부 장관 표창', affiliation: '대구보건고등학교/교사', name: '곽우은' },
  { year: 2024, honor: '중소벤처기업부 장관 표창', affiliation: '가톨릭대학교/교수', name: '성재열' },
  { year: 2024, honor: '중소벤처기업부 장관 표창', affiliation: '충남대학교/교수', name: '유태우' },
  { year: 2024, honor: '중소벤처기업부 장관 표창', affiliation: '한국벤처캐피탈협회/대리', name: '주윤미' },
  { year: 2024, honor: '중소벤처기업부 장관 표창', affiliation: '국토교통과학기술진흥원(단체)', name: '' },
  { year: 2024, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '케이저/대표', name: '견두헌' },
  { year: 2024, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '진접중학교/교사', name: '김효성' },
  { year: 2024, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '제이와이솔루션즈/대표', name: '윤지영' },
  { year: 2024, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '㈜카이아이컴퍼니/대표', name: '정호정' },
  { year: 2024, honor: '한국청년기업가정신재단 이사장 표창', affiliation: '㈜레페리/의장', name: '최인석' },

  { year: 2025, honor: '중소벤처기업부 장관 표창', affiliation: '충남대학교/교수', name: '김천규' },
  { year: 2025, honor: '중소벤처기업부 장관 표창', affiliation: '동명대학교/교수', name: '노성여' },
  { year: 2025, honor: '중소벤처기업부 장관 표창', affiliation: '서울대치초등학교/교사', name: '이주리' },
  { year: 2025, honor: '중소벤처기업부 장관 표창', affiliation: '안산국제비즈니스고등학교/교사', name: '정성욱' },
  { year: 2025, honor: '중소벤처기업부 장관 표창', affiliation: '유성구청 (단체)', name: '' },
  { year: 2025, honor: '한국청년기업가정신재단 이사장표창', affiliation: '원광대학교/교수', name: '김우순' },
  { year: 2025, honor: '한국청년기업가정신재단 이사장표창', affiliation: '정주고등학교/교수', name: '김윤섭' },
  { year: 2025, honor: '한국청년기업가정신재단 이사장표창', affiliation: '한국핵융합에너지연구원/선임행정원', name: '유성영' },
  { year: 2025, honor: '한국청년기업가정신재단 이사장표창', affiliation: '(재)세종창조경제혁신센터/책임', name: '윤재만' },
  { year: 2025, honor: '한국청년기업가정신재단 이사장표창', affiliation: '(재)대전창조경제혁신센터 (단체)', name: '' },
];