// store/useMenuStore.js
import { create } from 'zustand';
import { api as apiClient } from '../lib/apiClient.js';

/**
 * =============================================================================
 * useMenuStore - 메뉴 트리 데이터 전역 관리
 * =============================================================================
 *
 * 역할:
 * - 백엔드에서 받은 메뉴 트리를 Zustand로 관리
 * - 메뉴 데이터 로딩 상태 및 에러 핸들링
 * - 전체 앱에서 메뉴 데이터 접근 가능
 */

export const useMenuStore = create((set, get) => ({
  // 상태
  menuTree: null,
  flatMenuMap: {}, // menuId를 key로 하는 flat map (빠른 조회용)
  isLoading: false,
  error: null,

  // 메뉴 트리를 평탄화하여 menuId 맵 생성
  _buildFlatMap: (menuData) => {
    const flatMap = {};
    const buildFlatMap = (node) => {
      flatMap[node.menuId] = node;
      if (node.children && node.children.length > 0) {
        node.children.forEach(buildFlatMap);
      }
    };
    buildFlatMap(menuData);
    return flatMap;
  },

  // 메뉴 데이터 비동기 로드
  fetchMenuData: async () => {
    set({ isLoading: true, error: null });

    try {
      const response = await apiClient.get('/api/v1/menu');
      const menuData = response.data || response || mockMenuData; // TODO : mockMenuData 제거예정

      const flatMap = get()._buildFlatMap(menuData);

      set({
        menuTree: menuData,
        flatMenuMap: flatMap,
        isLoading: false,
      });

      return menuData;
    } catch (error) {
      console.error('메뉴 데이터 로드 실패, 목데이터 사용:', error);

      // TODO : 목데이터 제거예정
      const flatMap = get()._buildFlatMap(mockMenuData);

      set({
        menuTree: mockMenuData,
        flatMenuMap: flatMap,
        isLoading: false,
        error: error.message,
      });

      return mockMenuData;
    }
  },

  // menuId로 메뉴 노드 찾기
  getMenuById: (menuId) => {
    return get().flatMenuMap[menuId] || null;
  },

  // 메뉴 데이터 초기화
  resetMenu: () => {
    set({ menuTree: null, flatMenuMap: {}, error: null });
  },
}));

// 모의 메뉴 데이터 (테스트용) TODO : 삭제예정
export const mockMenuData = {
  'menuId': 'M_PIIO_00063',
  'menuNm': '사용자 최상위메뉴',
  'intgSysSeCd': 'PIIO',
  'mbrTypeCd': 'USR',
  'upMenuId': null,
  'iconClssNm': null,
  'sortSeq': 0,
  'upendMenuExpsrYn': 'N',
  'lfsdMenuExpsrYn': 'N',
  'scrnUseYn': 'Y',
  'scrnId': 'S_PIIO_00063',
  'scrnUrlAddr': '/',
  'scrnTypeCd': 'M',
  'upScrnId': null,
  'useYn': 'Y',
  'depth': 0,
  'children': [
    {
      'menuId': 'M_PIIO_00064',
      'menuNm': '신청·발급',
      'intgSysSeCd': 'PIIO',
      'mbrTypeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 1,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00064',
      'scrnUrlAddr': 'req',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00069',
          'menuNm': 'AI 스마트 검색',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00069',
          'scrnUrlAddr': 'ai',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00064',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00074',
              'menuNm': 'AI 스마트 검색',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00069',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00074',
              'scrnUrlAddr': 'ai-smart-search',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00069',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00070',
          'menuNm': '중소벤처기업부 지원사업 소개',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00070',
          'scrnUrlAddr': 'suprt',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00064',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00075',
              'menuNm': '지원사업',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00070',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00075',
              'scrnUrlAddr': 'UI_USR_L_010',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00070',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00071',
          'menuNm': '사업공고',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00071',
          'scrnUrlAddr': 'pbanc',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00064',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00076',
              'menuNm': '사업공고',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00071',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00076',
              'scrnUrlAddr': 'pbanc',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00071',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00072',
          'menuNm': '정책금융',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 4,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00072',
          'scrnUrlAddr': 'plcy',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00064',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00077',
              'menuNm': '정책금융안내',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00072',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00077',
              'scrnUrlAddr': 'UI_USR_L_030',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00072',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00073',
          'menuNm': '증명서 발급',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00064',
          'iconClssNm': null,
          'sortSeq': 5,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00073',
          'scrnUrlAddr': 'crtf',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00064',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00078',
              'menuNm': '증명서 발급',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00073',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00078',
              'scrnUrlAddr': 'UI_USR_L_040',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00073',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00079',
              'menuNm': '발급 진위 확인',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00073',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00079',
              'scrnUrlAddr': 'UI_USR_L_050',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00073',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00080',
              'menuNm': '기타증명서',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00073',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00080',
              'scrnUrlAddr': 'UI_USR_L_060',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00073',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00065',
      'menuNm': '정책정보',
      'intgSysSeCd': 'PIIO',
      'mbrTypeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 2,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00065',
      'scrnUrlAddr': 'plcy',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00081',
          'menuNm': '정책리포트',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00065',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00081',
          'scrnUrlAddr': 'reprt',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00065',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00084',
              'menuNm': '정책뉴스',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00081',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00084',
              'scrnUrlAddr': 'UI_USR_L_070',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00081',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00085',
              'menuNm': '행사정보',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00081',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00085',
              'scrnUrlAddr': 'UI_USR_L_190',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00081',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00086',
              'menuNm': '월간중기누리',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00081',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00086',
              'scrnUrlAddr': 'UI_USR_L_100',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00081',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00082',
          'menuNm': '품목·인증·규제',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00065',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00082',
          'scrnUrlAddr': 'icr',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00065',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00087',
              'menuNm': '입법·행정예고/고시',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00087',
              'scrnUrlAddr': 'UI_USR_L_110',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00082',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00088',
              'menuNm': '품목별 법정의무 인증제도',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00088',
              'scrnUrlAddr': 'UI_USR_L_120',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00082',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00089',
              'menuNm': '중소벤처기업부 법정민원신청',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00089',
              'scrnUrlAddr': 'UI_USR_W_130',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00082',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00090',
              'menuNm': '소재부품장비·뿌리기술·전문연구사업자 조회',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00082',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00090',
              'scrnUrlAddr': 'UI_USR_L_140',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00082',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00083',
          'menuNm': '더많은서비스',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00065',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00083',
          'scrnUrlAddr': 'mor',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00065',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00091',
              'menuNm': '주택특별공급 사업공고',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00083',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00091',
              'scrnUrlAddr': 'UI_USR_L_150',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00083',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00092',
              'menuNm': '유관시스템 둘러보기',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00083',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00092',
              'scrnUrlAddr': 'UI_USR_L_160',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00083',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00093',
              'menuNm': '기업업무용 서식',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00083',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00093',
              'scrnUrlAddr': 'UI_USR_L_170',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00083',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00094',
              'menuNm': '입주기업 모집공고',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00083',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00094',
              'scrnUrlAddr': 'UI_USR_L_180',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00083',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00066',
      'menuNm': '데이터 개방',
      'intgSysSeCd': 'PIIO',
      'mbrTypeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 3,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00066',
      'scrnUrlAddr': 'do',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00095',
          'menuNm': '정책정보 개방',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00066',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00095',
          'scrnUrlAddr': 'opn',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00066',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00096',
              'menuNm': 'API 안내',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00095',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00096',
              'scrnUrlAddr': 'UI_USR_L_210',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00095',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00097',
              'menuNm': '인증키 신청',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00095',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00097',
              'scrnUrlAddr': 'UI_USR_L_220',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00095',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00098',
              'menuNm': 'API Q&A',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00095',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00098',
              'scrnUrlAddr': 'UI_USR_L_230',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00095',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00067',
      'menuNm': '고객지원',
      'intgSysSeCd': 'PIIO',
      'mbrTypeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 3,
      'upendMenuExpsrYn': 'Y',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00067',
      'scrnUrlAddr': 'cs',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00099',
          'menuNm': '고객센터',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00067',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00099',
          'scrnUrlAddr': 'csc',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00067',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00101',
              'menuNm': '공지사항',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00101',
              'scrnUrlAddr': 'UI_USR_L_310',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00102',
              'menuNm': '자주 묻는 질문',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00102',
              'scrnUrlAddr': 'UI_USR_L_320',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00103',
              'menuNm': 'Q&A',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00103',
              'scrnUrlAddr': 'UI_USR_L_330',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00104',
              'menuNm': '콜센터안내',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00104',
              'scrnUrlAddr': 'UI_USR_L_340',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00105',
              'menuNm': '고객 만족도 조사',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00099',
              'iconClssNm': null,
              'sortSeq': 5,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00105',
              'scrnUrlAddr': 'UI_USR_R_341',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00099',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00100',
          'menuNm': '이용안내',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00067',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'Y',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00100',
          'scrnUrlAddr': 'info',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00067',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00106',
              'menuNm': '플랫폼 소개',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00100',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00106',
              'scrnUrlAddr': 'UI_USR_R_350',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00100',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00107',
              'menuNm': '이용가이드',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00100',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'Y',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00107',
              'scrnUrlAddr': 'UI_USR_R_360',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00100',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
      ],
    },
    {
      'menuId': 'M_PIIO_00068',
      'menuNm': '마이비즈니스',
      'intgSysSeCd': 'PIIO',
      'mbrTypeCd': 'USR',
      'upMenuId': 'M_PIIO_00063',
      'iconClssNm': null,
      'sortSeq': 5,
      'upendMenuExpsrYn': 'N',
      'lfsdMenuExpsrYn': 'Y',
      'scrnUseYn': 'Y',
      'scrnId': 'S_PIIO_00068',
      'scrnUrlAddr': 'mb',
      'scrnTypeCd': 'M',
      'upScrnId': 'S_PIIO_00063',
      'useYn': 'Y',
      'depth': 1,
      'children': [
        {
          'menuId': 'M_PIIO_00108',
          'menuNm': '나의 대시보드',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 1,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00108',
          'scrnUrlAddr': 'dash',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00112',
              'menuNm': 'AI맞춤추천공고',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00112',
              'scrnUrlAddr': 'UI_USR_L_480',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00108',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00113',
              'menuNm': '증명서 발급 조회',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00113',
              'scrnUrlAddr': 'UI_USR_L_510',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00108',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00114',
              'menuNm': '지원사업 신청 현황',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00108',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00114',
              'scrnUrlAddr': 'UI_USR_L_520',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00108',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00109',
          'menuNm': '회원정보관리',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 2,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00109',
          'scrnUrlAddr': 'mbr',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00115',
              'menuNm': '회원정보변경',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00115',
              'scrnUrlAddr': 'UI_USR_R_410',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00116',
              'menuNm': '비밀번호 수정',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00116',
              'scrnUrlAddr': 'UI_USR_R_420',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00117',
              'menuNm': '인증수단 재설정',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00117',
              'scrnUrlAddr': 'UI_USR_W_430',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00118',
              'menuNm': '회원탈퇴',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00109',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00118',
              'scrnUrlAddr': 'UI_USR_R_440',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00109',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00110',
          'menuNm': '기업정보관리',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 3,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00110',
          'scrnUrlAddr': 'cmp',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00119',
              'menuNm': '기업 기본정보',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00110',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00119',
              'scrnUrlAddr': 'UI_USR_R_450',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00110',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00120',
              'menuNm': '경영현황 분석',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00110',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00120',
              'scrnUrlAddr': 'UI_USR_R_490',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00110',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00121',
              'menuNm': '담당자 관리',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00110',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00121',
              'scrnUrlAddr': 'UI_USR_L_460',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00110',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00122',
              'menuNm': '문의 관리',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00110',
              'iconClssNm': null,
              'sortSeq': 4,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00122',
              'scrnUrlAddr': 'UI_USR_L_470',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00110',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
        {
          'menuId': 'M_PIIO_00111',
          'menuNm': '서비스 이용이력',
          'intgSysSeCd': 'PIIO',
          'mbrTypeCd': 'USR',
          'upMenuId': 'M_PIIO_00068',
          'iconClssNm': null,
          'sortSeq': 4,
          'upendMenuExpsrYn': 'N',
          'lfsdMenuExpsrYn': 'Y',
          'scrnUseYn': 'Y',
          'scrnId': 'S_PIIO_00111',
          'scrnUrlAddr': 'hsty',
          'scrnTypeCd': 'M',
          'upScrnId': 'S_PIIO_00068',
          'useYn': 'Y',
          'depth': 2,
          'children': [
            {
              'menuId': 'M_PIIO_00123',
              'menuNm': '관심 공고',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00111',
              'iconClssNm': null,
              'sortSeq': 1,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00123',
              'scrnUrlAddr': 'UI_USR_L_530',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00111',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00124',
              'menuNm': '나의 알림',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00111',
              'iconClssNm': null,
              'sortSeq': 2,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00124',
              'scrnUrlAddr': 'UI_USR_L_540',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00111',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
            {
              'menuId': 'M_PIIO_00125',
              'menuNm': '나의 Open API 신청내역',
              'intgSysSeCd': 'PIIO',
              'mbrTypeCd': 'USR',
              'upMenuId': 'M_PIIO_00111',
              'iconClssNm': null,
              'sortSeq': 3,
              'upendMenuExpsrYn': 'N',
              'lfsdMenuExpsrYn': 'Y',
              'scrnUseYn': 'Y',
              'scrnId': 'S_PIIO_00125',
              'scrnUrlAddr': 'UI_USR_L_550',
              'scrnTypeCd': 'T',
              'upScrnId': 'S_PIIO_00111',
              'useYn': 'Y',
              'depth': 3,
              'children': [],
            },
          ],
        },
      ],
    },
  ],
};
