export const JOINT_CERT_PROVIDER = Object.freeze({
  MAGICLINE: 'MAGICLINE',
});

export const JOINT_CERT_PURPOSE = Object.freeze({
  LOGIN: 'LOGIN',
  CERT_REGISTRATION: 'CERT_REGISTRATION',
  CERT_CHANGE: 'CERT_CHANGE',
});

export const JOINT_CERT_CLAIM = Object.freeze({
  SUBJECT_DN: 'SUBJECT_DN',
  ISSUER_DN: 'ISSUER_DN',
  SERIAL_NUMBER: 'SERIAL_NUMBER',
  POLICY_OID: 'POLICY_OID',
  SOURCE_TEXT: 'SOURCE_TEXT',
  DISPLAY_NAME: 'DISPLAY_NAME',
  ORGANIZATION_NAME: 'ORGANIZATION_NAME',
  BUSINESS_NUMBER: 'BUSINESS_NUMBER',
  VID_CHECK: 'VID_CHECK',
});

export const PROVIDER_CEREMONY_STATUS = Object.freeze({
  READY: 'READY',
  CLIENT_COMPLETED: 'CLIENT_COMPLETED',
  SERVER_VERIFIED: 'SERVER_VERIFIED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

export const CLIENT_PROVIDER_ERROR_CODE = Object.freeze({
  CLIENT_RUNTIME_NOT_CONFIGURED: 'CLIENT_RUNTIME_NOT_CONFIGURED',
  CLIENT_RUNTIME_UNAVAILABLE: 'CLIENT_RUNTIME_UNAVAILABLE',
  CLIENT_RUNTIME_INIT_FAILED: 'CLIENT_RUNTIME_INIT_FAILED',
  CLIENT_UNSUPPORTED_ENVIRONMENT: 'CLIENT_UNSUPPORTED_ENVIRONMENT',
  CLIENT_USER_CANCELLED: 'CLIENT_USER_CANCELLED',
  CLIENT_SIGN_FAILED: 'CLIENT_SIGN_FAILED',
  CLIENT_REQUEST_INVALID: 'CLIENT_REQUEST_INVALID',
  CLIENT_REQUEST_BUILD_FAILED: 'CLIENT_REQUEST_BUILD_FAILED',
  CLIENT_INTERNAL_ERROR: 'CLIENT_INTERNAL_ERROR',
});

export const SERVER_PROVIDER_ERROR_CODE = Object.freeze({
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNSUPPORTED_PROVIDER: 'UNSUPPORTED_PROVIDER',
  UNSUPPORTED_CAPABILITY: 'UNSUPPORTED_CAPABILITY',
  PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_VERIFICATION_FAILED: 'PROVIDER_VERIFICATION_FAILED',
  IDENTITY_MISMATCH: 'IDENTITY_MISMATCH',
  CLAIM_UNAVAILABLE: 'CLAIM_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

export const PROVIDER_ERROR_ORIGIN = Object.freeze({
  CLIENT_RUNTIME: 'CLIENT_RUNTIME',
  SERVER_VERIFICATION: 'SERVER_VERIFICATION',
});

export const FORBIDDEN_CONSUMER_FIELDS = Object.freeze([
  'loginAllowed',
  'memberMatched',
  'tokenIssued',
  'persistDn',
]);
